Home/urls.py
from django.urls import path

from Home import views

app_name = 'Home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

accounts/urls.py
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('editprofile/', UserEditProfileView.as_view(), name='eprofile'),
    path('profile/<int:id>', UserProfileView.as_view(), name='profile'),
    path('follow/<int:id>', UserFollowView.as_view(), name='follow'),
    path('unfollow/<int:id>', UserUnfollowView.as_view(), name='unfollow'),
    # password reset
    path('reset/', UserPasswordResetView.as_view(), name='password-reset'),
    path('reset/done/', UserPasswordResetDoneView.as_view(), name='password-reset-done'),
    path('confrim/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('confrim/complete/', UserPasswordResetCompleteView.as_view(), name='password-reset-complete'),
]

posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'
urlpatterns = [
    path('all/', PostListView.as_view(), name='all'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='detail'),
    path('reply/<slug:slug>/<int:comment_id>/', PostAddReplyView.as_view(), name='reply'),
    path('like/<slug:slug>', PostLikeView.as_view(), name='like'),
    path('update/<slug:slug>', PostUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>', PostDeleteView.as_view(), name='delete'),
]

socialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from .SizeValidation import file_size


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True, upload_to='profilepic/',validators=[file_size])
    bio = models.CharField(max_length=100, blank=True, null=True)
    age = models.PositiveIntegerField(blank=True, null=True)
    gender = models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, blank=True, null=True)


class Relation(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.follower} follows {self.following}'

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from accounts.models import Profile


class UserLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Username or email', 'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'password', 'class': 'form-control'}))


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    gender = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}),
                               choices=[('M', 'Male'), ('F', 'Female')])

    class Meta:
        model = Profile
        exclude = ['user']




class UserRegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError('this username is taken')
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('this email already exists')
        return email

    def clean(self):
        cd = super().clean()
        p1 = cd.get('password1')
        p2 = cd.get('password2')
        if p1 and p2 and p1 != p2:
            raise ValidationError('Passwords doesnt match')
        elif len(p1) < 8 and len(p2) < 8:
            raise ValidationError('Passwords must contain at least 8 characters')

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import View

from posts.models import Post
from .forms import UserRegisterForm, UserLoginForm, UserProfileForm
from .models import Relation


class UserRegisterView(View):
    form_class = UserRegisterForm
    template_name = 'register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.error(request, 'You are already registered', 'danger')
            return redirect('Home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create_user(username=cd['username'], password=cd['password1'], email=cd['email'])
            login(request, user)
            messages.success(request, 'you registered successfully!', 'success')
            return redirect('Home:home')
        return render(request, self.template_name, {'form': form})


class UserLoginView(View):
    template_name = 'login.html'
    form_class = UserLoginForm

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'you logged in', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('Home:home')
        messages.error(request, 'username or password incorrect', 'warning')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):

    def get(self, request):
        logout(request)
        messages.success(request, 'you logged out', 'success')
        return redirect('Home:home')


class UserEditProfileView(LoginRequiredMixin, View):
    template_name = 'editprofile.html'
    form_class = UserProfileForm

    def get(self, request):
        form = self.form_class(instance=request.user.profile, initial={'email': request.user.email,
                                                                       'first_name': request.user.first_name,
                                                                       'last_name': request.user.last_name})
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, instance=request.user.profile, files=request.FILES)
        if form.is_valid():
            form.save()
            cd = form.cleaned_data
            request.user.first_name = cd['first_name']
            request.user.last_name = cd['last_name']
            request.user.save()
            messages.success(request, 'Edited!', 'success')
            return redirect('accounts:profile', id=request.user.id)
        return render(request, self.template_name, {'form': form})


class UserProfileView(LoginRequiredMixin, View):
    template_name = 'profile.html'

    def get(self, request, id):
        is_following = False
        user = get_object_or_404(User, pk=id)
        posts = Post.objects.filter(author=user).order_by('-created').all()
        relation = Relation.objects.filter(follower=request.user, following=user).exists()
        if relation:
            is_following = True
        return render(request, self.template_name, {'user': user, 'is_following': is_following, 'posts': posts})


class UserFollowView(LoginRequiredMixin, View):
    def get(self, request, id):
        user = get_object_or_404(User, pk=id)
        relation = Relation.objects.filter(follower=request.user, following=user).exists()
        if relation:
            messages.error(request, f'You already followed {user.username}', 'error')
        else:
            Relation.objects.create(follower=request.user, following=user)
            messages.success(request, f'You followed {user.username}', 'success')
        return redirect('accounts:profile', id=id)


class UserUnfollowView(LoginRequiredMixin, View):
    def get(self, request, id):
        user = get_object_or_404(User, pk=id)
        relation = Relation.objects.filter(follower=request.user, following=user)
        if relation.exists():
            relation.delete()
            messages.success(request, f'You unfollowed {user.username}', 'success')
        else:
            messages.error(request, f'you are not following {user.username}', 'error')
        return redirect('accounts:profile', id=id)


class UserPasswordResetView(PasswordResetView):
    template_name = 'passReset/password_reset_form.html'
    success_url = reverse_lazy('accounts:password-reset-done')
    email_template_name = 'passReset/password_reset_email.html'


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'passReset/password_reset_done.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'passReset/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password-reset-complete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'passReset/password_reset_complete.html'

accounts/templates/editprofile.html
{% extends 'base.html' %}
{% block title %} Edit Profile {% endblock %}



{% block content %}

    <div >
        <form novalidate method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Edit" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}



{% block content %}

    <div >
        <form novalidate method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Login" class="btn btn-primary">
        </form>
        <a href="{% url 'accounts:password-reset' %}">Forgot Password?</a>
    </div>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ user }}`s  profile {% endblock %}



{% block content %}
    <div class="d-flex justify-content-center">
        <div class="d-inline-block position-relative">
            {% if user.profile.image %}
                <img class=" rounded-circle" style="width: 100px; height: 100px" src="{{ user.profile.image.url }}">
            {% else %}
                <img class=" rounded-circle" style="width: 100px; height: 100px" src=" {% static 'pic/userpic.png' %} ">
            {% endif %}
            {% if request.user.id == user.id %}
                <a href="{% url 'accounts:eprofile' %}">
                    <img class=" edit " style="width: 25px; height: 25px" src="{% static 'pic/edit.png' %}">
                </a>
            {% endif %}
        </div>
    </div>
    <h2 class="text-center pt-3">{{ user.username }}</h2>
    {% if user.profile.bio %}
        <p class="text-center">{{ user.profile.bio }}</p>
    {% endif %}
    {% if request.user.id != user.id and not is_following %}
        <a class="btn btn-primary d-flex justify-content-center" href="{% url 'accounts:follow' user.id %}">Follow</a>
    {% elif request.user.id != user.id and is_following %}
        <a class="btn btn-danger d-flex justify-content-center"
           href="{% url 'accounts:unfollow' user.id %}">Unfollow</a>
    {% endif %}
    <div class="d-flex justify-content-center align-center">
        <p class="p-3">{{ user.posts.count }} post</p>
        <p class="p-3">{{ user.following.count }} follower</p>
        <p class="p-3">{{ user.follower.count }} following</p>
    </div>
    {% if request.user.id == user.id %}
        <a href="{% url 'posts:create' %}" class="btn btn-primary d-flex justify-content-center">Create Post</a>
    {% endif %}
    <div class="row row-cols-3 p-2">
        {% for post in posts %}
            <div class=" col mb-3 bg-light  ">
                <div class="d-flex justify-content-start card-header align-items-end p-1  ">
                    {% if post.author.profile.image %}
                        <img class=" rounded-circle" style="width: 50px; height: 50px"
                             src="{{ post.author.profile.image.url }}">
                    {% else %}
                        <img class=" rounded-circle" style="width: 50px; height: 50px"
                             src="{% static 'pic/userpic.png' %}">
                    {% endif %}
                    <h5 class="text p-2">{{ post.author }} | {{ post.created|timesince }} ago</h5>

                </div>
                <a href="{{ post.get_absolute_url }}" class="text-decoration-none">
                    <div class="card-body">
                        <img src="{{ post.image.url }}" style="width: 400px; height: 250px">
                        <div class="d-flex justify-content-start align-items-center">
                            <h3 class="pt-3 link-dark ">{{ post.title }}</h3>
                </a>
                <a class="p-3 pt-0 pb-0 link-dark text-decoration-none "><img
                        src="{% static 'pic/chat.svg' %}"> {{ post.pcomments.count }}</a>
                {% if request.user.ulikes.exists %}
                    <a class=" link-dark text-decoration-none" href="{% url 'posts:like' post.slug %}"><img
                            src="{% static 'pic/liked.png' %}" style="width:25px; height:25px;">
                        {{ post.plikes.count }}</a>
                {% else %}
                    <a class=" link-dark text-decoration-none" href="{% url 'posts:like' post.slug %}"><img
                            src="{% static 'pic/heart.svg' %}">
                        {{ post.plikes.count }}</a>
                {% endif %}
            </div>
            <p class="p-3 pb-0 pt-0">{{ post.body|truncatewords:"5" }}</p>
            </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}
{% block title %} SignUp{% endblock %}



{% block content %}

    <div >
        <form novalidate method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="SignUp" class="btn btn-primary">
        </form>
    </div>
{% endblock %}