Home/urls.py
from django.urls import path

from Home import views

app_name = 'Home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

accounts/urls.py
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('editprofile/', UserEditProfileView.as_view(), name='eprofile'),
    path('profile/<int:id>', UserProfileView.as_view(), name='profile'),
    path('follow/<int:id>', UserFollowView.as_view(), name='follow'),
    path('unfollow/<int:id>', UserUnfollowView.as_view(), name='unfollow'),
    # password reset
    path('reset/', UserPasswordResetView.as_view(), name='password-reset'),
    path('reset/done/', UserPasswordResetDoneView.as_view(), name='password-reset-done'),
    path('confrim/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('confrim/complete/', UserPasswordResetCompleteView.as_view(), name='password-reset-complete'),
]

posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'
urlpatterns = [
    path('all/', PostListView.as_view(), name='all'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='detail'),
    path('reply/<slug:slug>/<int:comment_id>/', PostAddReplyView.as_view(), name='reply'),
    path('like/<slug:slug>', PostLikeView.as_view(), name='like'),
    path('update/<slug:slug>', PostUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>', PostDeleteView.as_view(), name='delete'),
]

socialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <h5 class="alert alert-{{ msg.tags }} text-center">{{ msg }}</h5>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<div class="d-flex justify-content-between align-items-center">
    <nav class="navbar justify-content-start">
    <a class="navbar-brand mb-0 h1" href="/">PGram</a>
    {% if not request.user.is_authenticated %}
      <a class="navbar-brand mb-0 h1" href="{% url 'accounts:login' %}">login</a>
      <a class="navbar-brand mb-0 h1" href="{% url 'accounts:register' %}">register</a>
    {% else %}
      <a class="navbar-brand mb-0 h1" href="{% url 'accounts:logout' %}">logout</a>
      <a class="navbar-brand mb-0 h1" href="{% url 'accounts:profile' request.user.id %}">profile</a>
      <a class="navbar-brand mb-0 h1" href="{% url 'posts:all' %}">posts</a>
    {% endif %}
    </nav>
    {% if  request.user.is_authenticated %} 
        <p>Welcome {{ request.user }}</p>
    {% endif %}
</div> 
<hr>