Home/urls.py
from django.urls import path

from Home import views

app_name = 'Home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

accounts/urls.py
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('editprofile/', UserEditProfileView.as_view(), name='eprofile'),
    path('profile/<int:id>', UserProfileView.as_view(), name='profile'),
    path('follow/<int:id>', UserFollowView.as_view(), name='follow'),
    path('unfollow/<int:id>', UserUnfollowView.as_view(), name='unfollow'),
    # password reset
    path('reset/', UserPasswordResetView.as_view(), name='password-reset'),
    path('reset/done/', UserPasswordResetDoneView.as_view(), name='password-reset-done'),
    path('confrim/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('confrim/complete/', UserPasswordResetCompleteView.as_view(), name='password-reset-complete'),
]

posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'
urlpatterns = [
    path('all/', PostListView.as_view(), name='all'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='detail'),
    path('reply/<slug:slug>/<int:comment_id>/', PostAddReplyView.as_view(), name='reply'),
    path('like/<slug:slug>', PostLikeView.as_view(), name='like'),
    path('update/<slug:slug>', PostUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>', PostDeleteView.as_view(), name='delete'),
]

socialMedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy
from django.utils.text import slugify

from .SizeValidation import file_size


class Post(models.Model):
    title = models.CharField(max_length=75, unique=True)
    image = models.ImageField(upload_to='posts/image/', validators=[file_size])
    body = models.CharField(max_length=250)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    slug = models.SlugField(unique=True, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.slug = slugify(self.title)
        super(Post, self).save()

    def get_absolute_url(self):
        return reverse_lazy('posts:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.author} -- {self.body[:50]}'

    class Meta:
        ordering = ['-created']


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments',
                              null=True, blank=True)
    is_reply = models.BooleanField(default=False)
    body = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.is_reply:
            return f'{self.reply.author} replied to {self.reply}'
        else:
            return f'{self.author} commented to {self.post}'

    class Meta:
        ordering = ['-created']


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='plikes')
    liked_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ulikes')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.liked_by} liked {self.post.slug}'

posts/forms.py
from django import forms

from posts.models import Comment, Post


class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.TextInput(attrs={'label': 'message', 'class': 'form-control'}),
        }


class ReplyCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.TextInput(attrs={'label': 'message', 'class': 'form-control'}),
        }


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'image', 'body',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control', 'required': True}),
            'body': forms.TextInput(attrs={'class': 'form-control'}),
        }

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import ListView

from posts.forms import *
from posts.models import Post, Comment, Like


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'posts/posts.html'
    context_object_name = 'posts'


class PostDetailView(LoginRequiredMixin, View):
    template_name = 'posts/detail.html'
    context_object_name = 'post'
    form_class = CreateCommentForm
    form_class_reply = ReplyCommentForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, slug=kwargs['slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = Comment.objects.filter(post=self.post_instance, is_reply=False)
        return render(request, self.template_name, {'post': self.post_instance, 'comments': comments,
                                                    'form': self.form_class, 'reply_form': self.form_class_reply})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = self.post_instance
            comment.author = request.user
            comment.save()
            messages.success(request, 'your comment sended', 'success')
        return redirect('posts:detail', self.post_instance.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = ReplyCommentForm

    def post(self, request, slug, comment_id):
        comment = get_object_or_404(Comment, pk=comment_id)
        cpost = get_object_or_404(Post, slug=slug)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.post = cpost
            reply.author = request.user
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'your reply sended', 'success')
        return redirect('posts:detail', cpost.slug)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        like = Like.objects.filter(post=post, liked_by=request.user)
        if like.exists():
            like.delete()
            messages.success(request, 'disliked', 'success')
        else:
            Like.objects.create(post=post, liked_by=request.user)
            messages.success(request, 'Liked', 'success')
        return redirect('posts:detail', post.slug)


class PostCreateView(LoginRequiredMixin, View):
    template_name = 'posts/post_create.html'
    form_class = PostForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, files=request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, 'Post created', 'success')
            return redirect('posts:detail', post.slug)
        return render(request, self.template_name, {'form': form})


class PostUpdateView(LoginRequiredMixin, View):
    template_name = 'posts/post_update.html'
    form_class = PostForm

    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug, author=self.request.user)
        form = self.form_class(instance=post, initial={'image': post.image.url})
        return render(request, self.template_name, {'form': form})

    def post(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        form = self.form_class(request.POST, files=request.FILES, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post updated', 'success')
            return redirect('posts:detail', post.slug)
        return render(request, self.template_name, {'form': form})


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug= slug)
        if post.author.id == request.user.id:
            post.delete()
            messages.success(request, 'post deleted successfully', 'success')
        else:
            messages.error(request, 'you cant delete this post', 'danger')
        return redirect('accounts:profile', request.user.id)

posts/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} All Posts {% endblock %}

{% block content %}
    <div class="card mb-3">
        <div class="d-flex justify-content-start card-header align-items-center p-1">
            <a href="{% url 'accounts:profile' post.author.id %}">
            {% if post.author.profile.image %}
                <img class=" rounded-circle" style="width: 50px; height: 50px"
                     src="{{ post.author.profile.image.url }}">
            {% else %}
                <img class=" rounded-circle" style="width: 50px; height: 50px" src="{% static 'pic/userpic.png' %}">
            {% endif %}</a>
            <h5 class="text p-2">{{ post.author }} | {{ post.created|timesince }} ago</h5>
            {% if request.user == post.author %}
                <a class="btn btn-info p-2 m-1 text-white" href="{% url 'posts:update' post.slug %}">Update</a>
                <a class="btn btn-danger p-2" href="{% url 'posts:delete' post.slug %}" onclick="postDelete()">Delete</a>
            {% endif %}
        </div>
            <div class="card-body">
                <img src="{{ post.image.url }}" style="width: 400px; height: 250px">
                <div class="d-flex justify-content-start align-items-center">
                    <h3 class="pt-3 link-dark ">{{ post.title }}</h3>

        <div class="p-3">
            <img src="{% static 'pic/Chat.svg' %}"> {{ post.pcomments.count }}
        </div>
        {% if request.user.ulikes.exists %}
            <a class=" link-dark text-decoration-none" href="{% url 'posts:like' post.slug %}"><img
                    src="{% static 'pic/liked.png' %}" style="width:25px; height:25px;">
                {{ post.plikes.count }}</a>
        {% else %}
            <a class=" link-dark text-decoration-none" href="{% url 'posts:like' post.slug %}"><img
                    src="{% static 'pic/Heart.svg' %}">
                {{ post.plikes.count }}</a>
        {% endif %}
    </div>
    <p class="p-3 pb-0 pt-0">{{ post.body }}</p>
    </div>
    <hr>
    <div class="p-3">
        <h4>Send Comment</h4>
        <form method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Send">
        </form>
    </div>
    </div>
    {% for comment in comments %}
        <div class="card bg-dark text-white mb-2">
        <div class="d-flex justify-content-start card-header align-items-end p-1">
            {% if comment.author.profile.image %}
                <img class=" rounded-circle" style="width: 50px; height: 50px"
                     src="{{ comment.author.profile.image.url }}">
            {% else %}
                <img class=" rounded-circle" style="width: 50px; height: 50px" src="{% static 'pic/userpic.png' %}">
            {% endif %}
            <h5 class="text p-2">{{ comment.author }} | {{ comment.created|timesince }} ago</h5>
        </div>
        <div class="card-body">
            <p>{{ comment.body }}</p>
        </div>
        <hr>
        <div class="p-3">
            <h4>Send Reply</h4>
            <form method="post" action="{% url 'posts:reply' post.slug comment.id %}">
                {% csrf_token %}
                {{ reply_form.as_p }}
                <input type="submit" class="btn btn-primary" value="Send">
            </form>
        </div>
        {% with replies=comment.rcomments.all %}
            {% for reply in replies %}
                <div class="card bg-light-subtle  m-2">
                <div class="d-flex justify-content-start card-header align-items-center p-1">
                    <img src="{% static 'pic/reply.png' %}" style="width: 30px; height: 30px">
                    {% if reply.auther.profile.image.exists %}
                        <img class=" rounded-circle" style="width: 50px; height: 50px"
                             src="{{ reply.author.profile.image.url }}">
                    {% else %}
                        <img class=" rounded-circle" style="width: 50px; height: 50px"
                             src="{% static 'pic/userpic.png' %}">
                    {% endif %}
                    <h5 class="text p-2">{{ reply.author }} | {{ reply.created|timesince }} ago</h5>
                </div>
                <div class="card-body">
                    <p>{{ reply.body }}</p>
                </div> <br>
            {% endfor %}
        {% endwith %}
    </div><br/>
    {% empty %}
        <h5>No Comment yet!</h5>
    {% endfor %}
    <script>
        function postDelete(){
            let n = confirm('are you sure?');
        }

    </script>
{% endblock %}

posts/templates/posts/post_create.html
{% extends 'base.html' %}
{% block title %} Create New Post {% endblock %}

{% block content %}
    <div >
        <form novalidate method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

posts/templates/posts/post_update.html
{% extends 'base.html' %}
{% block title %} update Post {% endblock %}

{% block content %}
    <div >
        <form novalidate method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

posts/templates/posts/posts.html
{% extends 'base.html' %}
{% load static %}
{% block title %} All Posts {% endblock %}

{% block content %}
    <div class="row row-cols-3 justify-content-center">
        {% for post in posts %}
            <div class=" col bg-light ">
                <div class="d-flex justify-content-start card-header align-items-end p-1  ">
                    {% if post.author.profile.image %}
                        <img class=" rounded-circle" style="width: 50px; height: 50px"
                             src="{{ post.author.profile.image.url }}">
                    {% else %}
                        <img class=" rounded-circle" style="width: 50px; height: 50px"
                             src="{% static 'pic/userpic.png' %}">
                    {% endif %}
                    <h5 class="text p-2">{{ post.author }} | {{ post.created|timesince }} ago</h5>

                </div>
                <a href="{{ post.get_absolute_url }}" class="text-decoration-none">
                    <div class="card-body">
                        <img src="{{ post.image.url }}" style="width: 400px; height: 250px">
                        <div class="d-flex justify-content-start align-items-center">
                            <h3 class="pt-3 link-dark ">{{ post.title }}</h3>
                </a>
                <a class="p-3 pt-0 pb-0 link-dark text-decoration-none "><img
                        src="{% static 'pic/Chat.svg' %}"> {{ post.pcomments.count }}</a>
                {% if request.user.ulikes.exists %}
                    <a class=" link-dark text-decoration-none" href="{% url 'posts:like' post.slug %}"><img
                            src="{% static 'pic/liked.png' %}" style="width:25px; height:25px;">
                        {{ post.plikes.count }}</a>
                {% else %}
                    <a class=" link-dark text-decoration-none" href="{% url 'posts:like' post.slug %}"><img
                            src="{% static 'pic/Heart.svg' %}">
                        {{ post.plikes.count }}</a>
                {% endif %}
            </div>
            <p class="p-3 pb-0 pt-0">{{ post.body|truncatewords:"5" }}</p>
            </div>
            </div>
        {% empty %}
            <div class="d-flex justify-content-center">
            <h3 class="">No Post Yet!</h3>
            </div>
        {% endfor %}
    </div>
{% endblock %}